### ISSUE TITLE
Open google maps for direction

### ISSUE THREAD

**Issue by jayahariv** [jayahariv/clean-kerala#2]
If the user wants to go to the toilet, show direction to go.

Acceptance
- On click annotation, they should see an annotation view with the direction button. 
- On click direction button, the app should open google map app or safari with the current location and destination address.

**Comment by FraDeliro** [comment]
If you agree I can take it :) Thanks.

**Comment by jayahariv** [comment]
thanks, @FraDeliro, please. let me know if you have any questions.

**Comment by jayahariv** [comment]
thank you @FraDeliro
